// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNvwpIR42NJ45EEC82DJl150n6t74gxr8',
    appId: '1:244510802628:web:d6f59e785a01965f13bf91',
    messagingSenderId: '244510802628',
    projectId: 'flutterauth-44bd2',
    authDomain: 'flutterauth-44bd2.firebaseapp.com',
    storageBucket: 'flutterauth-44bd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6fDQdgBh7lvXlDh3jLcv5I5syztJttc',
    appId: '1:244510802628:android:ea855631ba2c9bbd13bf91',
    messagingSenderId: '244510802628',
    projectId: 'flutterauth-44bd2',
    storageBucket: 'flutterauth-44bd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzO_YL-LcjxwHEdbvw0YidQdz3NSKIE2U',
    appId: '1:244510802628:ios:0cd0ffe43448d46613bf91',
    messagingSenderId: '244510802628',
    projectId: 'flutterauth-44bd2',
    storageBucket: 'flutterauth-44bd2.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzO_YL-LcjxwHEdbvw0YidQdz3NSKIE2U',
    appId: '1:244510802628:ios:5de831fda6f990ab13bf91',
    messagingSenderId: '244510802628',
    projectId: 'flutterauth-44bd2',
    storageBucket: 'flutterauth-44bd2.appspot.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
